Repository agusarcejas/recalc, pull requests merged in 2023-05, with the labels that each got.

#10 Fix/div
  .github/workflows/main.yml
  .gitignore
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/api.js
  src/controllers.js
  src/core.js
  src/models.js
  src/seed.js
  src/server.js
  test/api.test.js
  test/models.test.js
Labels: bug

#11 fix 2 de la funcion div y el test div
  src/core.js
  test/core.test.js
Labels: bug

#12 Test de resta negativa
  src/controllers.js
  test/core.test.js
Labels: enhancement

#13 Agrego test que verifica la multiplicacion con un parametro negativo
  test/core.test.js
Labels: enhancement

#15 Fix/second arg
  src/models.js
  test/models.test.js
Labels: bug, enhancement

#16 Feature/error history
  src/models.js
  test/models.test.js
Labels: enhancement

#17 Feature/obtener historial
  src/models.js
  test/models.test.js
Labels: enhancement

#18 Feature/delete history
  src/models.js
  test/models.test.js
Labels: enhancement

#19 Feature/endpoint add
  src/controllers.js
  test/api.test.js
Labels: bug, enhancement

#20 Feature/endpoint mul
  src/controllers.js
  test/api.test.js
Labels: enhancement

#21 Feature/endpoint div
  src/controllers.js
  test/api.test.js
Labels: enhancement

#22 Feature/endpoint pow
  src/controllers.js
  test/api.test.js
Labels: enhancement
