Repository agusarcejas/recalc, pull requests merged in 2023-06, with the labels that each got.

#23 Arreglo conflicto surgido al hacer fork
  src/controllers.js
Labels: bug

#24 Feature/calculate add
  src/models.js
  src/public/index.html
  src/public/index.js
  test/ui.test.js
Labels: bug, enhancement

#25 Feature/calculate mul
  src/public/index.js
  test/ui.test.js
Labels: enhancement

#26 Feature/calculate div
  src/public/index.js
  test/ui.test.js
Labels: enhancement

#27 Feature/calculate pow
  src/public/index.html
  src/public/index.js
  test/ui.test.js
Labels: enhancement

#29 Test/eslint
  .eslintrc.cjs
  src/api.js
  src/public/index.js
Labels: enhancement

#30 Feature/button c
  src/public/index.js
  test/ui.test.js
Labels: enhancement

#31 Dev
  .eslintrc.cjs
  CHANGELOG.md
  README.md
  package.json
  src/api.js
  src/controllers.js
  src/models.js
  src/public/index.html
  src/public/index.js
  test/ui.test.js
Labels: documentation
